### ISSUE TITLE
updates for matrix based meetings

### ISSUE THREAD

**Issue by dustymabe** [coreos/fcos-meeting-action#60]
Since we moved to matrix a few things need to change:

- all commands now need `!` instead of `#` in front
- the `!chair` command might not exist(doesn't do anything) any longer
- the directives for channels need updated links
    - Fedora CoreOS room link: https://matrix.to/#/#coreos:fedoraproject.org
    - Fedora meeting 1 room link: https://matrix.to/#/#meeting-1:fedoraproject.org
        - this link should go in the message we post to notify people about the meeting
- the `fcosmeetinghtml()` should get updated to accept the new meeting html from the matrix bot. It kind of works right now but doesn't properly hyperlink things in the discussion forum post.

**Comment by prestist** [comment]
Closed by https://github.com/coreos/fcos-meeting-action/pull/61
